spec:
  template:
    spec:
      containers:
        - resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 200Mi
          env:
            - name: DEPLOYMENT_PATH
              value: /deployments/config/app-config.yml
          volumeMounts:
            - name: config
              mountPath: /deployments/config/
      volumes:
        - configMap:
            name: project-service
          name: config
